language: python

python: 3.6

cache: pip

before_install:
  - pip install --upgrade pip && pip install -r requirements.txt

before_script:
  - flake8 .

script:
  - python check_isa.py
  - python check_dpkg.py
